use_frameworks!
source 'git@git.iliunian.cn:apple/NLSpecs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '9.3'

target 'NUKit_Example' do
  pod 'NUKit', :path => '../'

  target 'NUKit_Tests' do
    inherit! :search_paths

    
  end
end
