use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/liunina/NLSpecs.git'

platform :ios, '9.3'

target 'NUKit_Example' do
  pod 'NUKit', :path => '../'

  target 'NUKit_Tests' do
    inherit! :search_paths

    
  end
end
